<template><div><h1 id="client" tabindex="-1"><a class="header-anchor" href="#client"><span>Client</span></a></h1>
<h2 id="rust" tabindex="-1"><a class="header-anchor" href="#rust"><span>Rust</span></a></h2>
<p>Through client code, you can easily interact with Jito Restaking Program.</p>
<p><strong>Example</strong>:</p>
<p>Initializing NCN:</p>
<div class="language-rust line-numbers-mode" data-highlighter="prismjs" data-ext="rs" data-title="rs"><pre v-pre><code><span class="line"><span class="token keyword">use</span> <span class="token namespace">jito_restaking_client<span class="token punctuation">::</span>instructions<span class="token punctuation">::</span></span><span class="token class-name">InitializeNcnBuilder</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">use</span> <span class="token namespace">jito_restaking_core<span class="token punctuation">::</span></span><span class="token punctuation">{</span><span class="token namespace">config<span class="token punctuation">::</span></span><span class="token class-name">Config</span><span class="token punctuation">,</span> <span class="token namespace">ncn<span class="token punctuation">::</span></span><span class="token class-name">Ncn</span><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">use</span> <span class="token namespace">solana_rpc_client<span class="token punctuation">::</span>rpc_client<span class="token punctuation">::</span></span><span class="token class-name">RpcClient</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">use</span> <span class="token namespace">solana_sdk<span class="token punctuation">::</span></span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token namespace">commitment_config<span class="token punctuation">::</span></span><span class="token class-name">CommitmentConfig</span><span class="token punctuation">,</span></span>
<span class="line">    pubkey<span class="token punctuation">,</span></span>
<span class="line">    <span class="token namespace">pubkey<span class="token punctuation">::</span></span><span class="token class-name">Pubkey</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token namespace">signature<span class="token punctuation">::</span></span><span class="token punctuation">{</span>read_keypair_file<span class="token punctuation">,</span> <span class="token class-name">Keypair</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token namespace">signer<span class="token punctuation">::</span></span><span class="token class-name">Signer</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token namespace">transaction<span class="token punctuation">::</span></span><span class="token class-name">Transaction</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">fn</span> <span class="token function-definition function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> restaking_program_id <span class="token operator">=</span> <span class="token macro property">pubkey!</span><span class="token punctuation">(</span><span class="token string">"RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> rpc_client <span class="token operator">=</span> <span class="token class-name">RpcClient</span><span class="token punctuation">::</span><span class="token function">new_with_commitment</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token string">"https://api.devnet.solana.com"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token class-name">CommitmentConfig</span><span class="token punctuation">::</span><span class="token function">confirmed</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> keypair <span class="token operator">=</span> <span class="token function">read_keypair_file</span><span class="token punctuation">(</span><span class="token string">"~/.config/solana/id.json"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// Initialize NCN</span></span>
<span class="line">    <span class="token function">initialize_ncn</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>restaking_program_id<span class="token punctuation">,</span> <span class="token operator">&amp;</span>rpc_client<span class="token punctuation">,</span> <span class="token operator">&amp;</span>keypair<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">fn</span> <span class="token function-definition function">initialize_ncn</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Pubkey</span><span class="token punctuation">,</span> rpc_client<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">RpcClient</span><span class="token punctuation">,</span> keypair<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Keypair</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> base <span class="token operator">=</span> <span class="token class-name">Keypair</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> ncn <span class="token operator">=</span> <span class="token class-name">Ncn</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> <span class="token keyword">mut</span> ix_builder <span class="token operator">=</span> <span class="token class-name">InitializeNcnBuilder</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> ix <span class="token operator">=</span> ix_builder</span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">config</span><span class="token punctuation">(</span><span class="token class-name">Config</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">ncn</span><span class="token punctuation">(</span>ncn<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">admin</span><span class="token punctuation">(</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">base</span><span class="token punctuation">(</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">instruction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> blockhash <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">get_latest_blockhash</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token class-name">Transaction</span><span class="token punctuation">::</span><span class="token function">new_signed_with_payer</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>ix<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token class-name">Some</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>keypair<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        blockhash<span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> result <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">send_and_confirm_transaction</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>tx<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token macro property">println!</span><span class="token punctuation">(</span><span class="token string">"{:?}"</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


