<template><div><h1 id="rust-client" tabindex="-1"><a class="header-anchor" href="#rust-client"><span>Rust Client</span></a></h1>
<h2 id="jito-restaking-client" tabindex="-1"><a class="header-anchor" href="#jito-restaking-client"><span>Jito Restaking Client</span></a></h2>
<p>Through <code v-pre>jito-restaking-client</code>, you can handle the operation of NCN and Operator such as registering, making relationship with Vault.</p>
<p><strong>Example</strong>:</p>
<p>Initializing NCN:</p>
<div class="language-rust line-numbers-mode" data-highlighter="prismjs" data-ext="rs" data-title="rs"><pre v-pre><code><span class="line"><span class="token keyword">fn</span> <span class="token function-definition function">initialize_ncn</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Pubkey</span><span class="token punctuation">,</span> rpc_client<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">RpcClient</span><span class="token punctuation">,</span> keypair<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Keypair</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> base <span class="token operator">=</span> <span class="token class-name">Keypair</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> ncn <span class="token operator">=</span> <span class="token class-name">Ncn</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> <span class="token keyword">mut</span> ix_builder <span class="token operator">=</span> <span class="token class-name">InitializeNcnBuilder</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> ix <span class="token operator">=</span> ix_builder</span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">config</span><span class="token punctuation">(</span><span class="token class-name">Config</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">ncn</span><span class="token punctuation">(</span>ncn<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">admin</span><span class="token punctuation">(</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">base</span><span class="token punctuation">(</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">instruction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> blockhash <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">get_latest_blockhash</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token class-name">Transaction</span><span class="token punctuation">::</span><span class="token function">new_signed_with_payer</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>ix<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token class-name">Some</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>keypair<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        blockhash<span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> result <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">send_and_confirm_transaction</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>tx<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token macro property">println!</span><span class="token punctuation">(</span><span class="token string">"{:?}"</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Initializing Operator:</p>
<div class="language-rust line-numbers-mode" data-highlighter="prismjs" data-ext="rs" data-title="rs"><pre v-pre><code><span class="line"><span class="token keyword">fn</span> <span class="token function-definition function">initialize_operator</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Pubkey</span><span class="token punctuation">,</span> rpc_client<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">RpcClient</span><span class="token punctuation">,</span> keypair<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Keypair</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> base <span class="token operator">=</span> <span class="token class-name">Keypair</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> operator <span class="token operator">=</span> <span class="token class-name">Operator</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> <span class="token keyword">mut</span> ix_builder <span class="token operator">=</span> <span class="token class-name">InitializeOperatorBuilder</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> ix <span class="token operator">=</span> ix_builder</span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">config</span><span class="token punctuation">(</span><span class="token class-name">Config</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>restaking_program_id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">operator</span><span class="token punctuation">(</span>operator<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">admin</span><span class="token punctuation">(</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">base</span><span class="token punctuation">(</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">operator_fee_bps</span><span class="token punctuation">(</span><span class="token number">1_000</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">instruction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> blockhash <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">get_latest_blockhash</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token class-name">Transaction</span><span class="token punctuation">::</span><span class="token function">new_signed_with_payer</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>ix<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token class-name">Some</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>keypair<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        blockhash<span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> result <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">send_and_confirm_transaction</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>tx<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token macro property">println!</span><span class="token punctuation">(</span><span class="token string">"{:?}"</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="jito-vault-client" tabindex="-1"><a class="header-anchor" href="#jito-vault-client"><span>Jito Vault Client</span></a></h2>
<p>Through <code v-pre>jito-vault-client</code>, you can handle the operation of Vault such as minting VRT, withdrawing.</p>
<p><strong>Example</strong>:</p>
<p>Initializing Vault:</p>
<div class="language-rust line-numbers-mode" data-highlighter="prismjs" data-ext="rs" data-title="rs"><pre v-pre><code><span class="line"><span class="token keyword">fn</span> <span class="token function-definition function">initialize_vault</span><span class="token punctuation">(</span></span>
<span class="line">    vault_program_id<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Pubkey</span><span class="token punctuation">,</span></span>
<span class="line">    rpc_client<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">RpcClient</span><span class="token punctuation">,</span></span>
<span class="line">    keypair<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Keypair</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">)</span> <span class="token punctuation">-></span> <span class="token punctuation">(</span><span class="token class-name">Pubkey</span><span class="token punctuation">,</span> <span class="token class-name">Pubkey</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> base <span class="token operator">=</span> <span class="token class-name">Keypair</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> vault <span class="token operator">=</span> <span class="token class-name">Vault</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>vault_program_id<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> vrt_mint <span class="token operator">=</span> <span class="token class-name">Keypair</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> token_mint <span class="token operator">=</span> <span class="token macro property">pubkey!</span><span class="token punctuation">(</span><span class="token string">"HSkJ5428nHAvWsWA1AjeFuh79STnuUMvs4APoyAZXbkK"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> <span class="token keyword">mut</span> ix_builder <span class="token operator">=</span> <span class="token class-name">InitializeVaultBuilder</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> ix <span class="token operator">=</span> ix_builder</span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">config</span><span class="token punctuation">(</span><span class="token class-name">Config</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span>vault_program_id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">vault</span><span class="token punctuation">(</span>vault<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">vrt_mint</span><span class="token punctuation">(</span>vrt_mint<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">token_mint</span><span class="token punctuation">(</span>token_mint<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">admin</span><span class="token punctuation">(</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">base</span><span class="token punctuation">(</span>base<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">deposit_fee_bps</span><span class="token punctuation">(</span><span class="token number">1_000</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">withdrawal_fee_bps</span><span class="token punctuation">(</span><span class="token number">1_000</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">reward_fee_bps</span><span class="token punctuation">(</span><span class="token number">1_000</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">decimals</span><span class="token punctuation">(</span><span class="token number">9</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">instruction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> blockhash <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">get_latest_blockhash</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token class-name">Transaction</span><span class="token punctuation">::</span><span class="token function">new_signed_with_payer</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>ix<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token class-name">Some</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span>keypair<span class="token punctuation">,</span> <span class="token operator">&amp;</span>base<span class="token punctuation">,</span> <span class="token operator">&amp;</span>vrt_mint<span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        blockhash<span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> result <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">send_and_confirm_transaction</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>tx<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token macro property">println!</span><span class="token punctuation">(</span><span class="token string">"{:?}"</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token punctuation">(</span>vault<span class="token punctuation">,</span> vrt_mint<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Create Token Metadata:</p>
<div class="language-rust line-numbers-mode" data-highlighter="prismjs" data-ext="rs" data-title="rs"><pre v-pre><code><span class="line"><span class="token keyword">fn</span> <span class="token function-definition function">create_token_metadata</span><span class="token punctuation">(</span>rpc_client<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">RpcClient</span><span class="token punctuation">,</span> keypair<span class="token punctuation">:</span> <span class="token operator">&amp;</span><span class="token class-name">Keypair</span><span class="token punctuation">,</span> pubkeys<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token class-name">Pubkey</span><span class="token punctuation">,</span> <span class="token class-name">Pubkey</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> inline_mpl_token_metadata_id <span class="token operator">=</span> <span class="token macro property">pubkey!</span><span class="token punctuation">(</span><span class="token string">"metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> metadata <span class="token operator">=</span> <span class="token class-name">Pubkey</span><span class="token punctuation">::</span><span class="token function">find_program_address</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token operator">&amp;</span><span class="token punctuation">[</span></span>
<span class="line">            <span class="token string">b"metadata"</span><span class="token punctuation">,</span></span>
<span class="line">            inline_mpl_token_metadata_id<span class="token punctuation">.</span><span class="token function">as_ref</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            pubkeys<span class="token number">.1</span><span class="token punctuation">.</span><span class="token function">as_ref</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token operator">&amp;</span>inline_mpl_token_metadata_id<span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> <span class="token keyword">mut</span> ix_builder <span class="token operator">=</span> <span class="token class-name">CreateTokenMetadataBuilder</span><span class="token punctuation">::</span><span class="token function">new</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> ix <span class="token operator">=</span> ix_builder</span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">vault</span><span class="token punctuation">(</span>pubkeys<span class="token number">.0</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">admin</span><span class="token punctuation">(</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">vrt_mint</span><span class="token punctuation">(</span>pubkeys<span class="token number">.1</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">payer</span><span class="token punctuation">(</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">metadata</span><span class="token punctuation">(</span>metadata<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token class-name">String</span><span class="token punctuation">::</span><span class="token function">from</span><span class="token punctuation">(</span><span class="token string">"Hello"</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token class-name">String</span><span class="token punctuation">::</span><span class="token function">from</span><span class="token punctuation">(</span><span class="token string">"HLO"</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">uri</span><span class="token punctuation">(</span><span class="token class-name">String</span><span class="token punctuation">::</span><span class="token function">from</span><span class="token punctuation">(</span><span class="token string">"https://..."</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">.</span><span class="token function">instruction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> blockhash <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">get_latest_blockhash</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">let</span> tx <span class="token operator">=</span></span>
<span class="line">        <span class="token class-name">Transaction</span><span class="token punctuation">::</span><span class="token function">new_signed_with_payer</span><span class="token punctuation">(</span><span class="token operator">&amp;</span><span class="token punctuation">[</span>ix<span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token class-name">Some</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>keypair<span class="token punctuation">.</span><span class="token function">pubkey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token operator">&amp;</span><span class="token punctuation">[</span>keypair<span class="token punctuation">]</span><span class="token punctuation">,</span> blockhash<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">let</span> result <span class="token operator">=</span> rpc_client<span class="token punctuation">.</span><span class="token function">send_and_confirm_transaction</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>tx<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">unwrap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token macro property">println!</span><span class="token punctuation">(</span><span class="token string">"{:?}"</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


